### ISSUE TITLE
Face recognition is not working

### ISSUE THREAD

**Issue by amsuvarna27** [nischi/MMM-Face-Reco-DNN#38] opened 2020-05-03 05:34 UTC
In my Magic mirror project I'm using this module to hide and unhide module.
The classes: default and classes:"my name" is working.
But when I use classes:"everyone" it's not working.
Any solution.
What I need is...
If no one is infornt of mirror only clock module should be shown
If any motion detected or any unknown user came whom I dint added in datasets....that time it should show temperature, news feed, compliments and calendar.
I made clock as default and other module as everyone.
It's not working.

**Comment by nischi** [comment] 2020-05-05 04:08
@amsuvarna27 Is that maybe a duplicate of #36?

**Closed** 2020-08-20 09:17 UTC
Labels: bug, duplicate
